apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    uid: timescaledb
    url: timescaledb:5432
    database: egx_market
    user: postgres
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: postgres
